# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QMaxentPlugin
                                 A QGIS plugin
 This plugin allows users to build species distribution models (SDMs) directly within QGIS using the MaxEnt (Maximum Entropy) approach. It provides an intuitive interface to load presence data, sample background points, extract environmental variables from raster layers, and run machine learning models to predict suitable habitats. Results are visualized as raster layers and can be evaluated using AUC, ROC, and feature importance plots.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-23
        copyright            : (C) 2025 by Byeong-Hyeok Yu
        email                : bhyu@knps.or.kr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QMaxentPlugin class from file QMaxentPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qmaxent import QMaxentPlugin
    return QMaxentPlugin(iface)
